version: '3'

services:
    # rabbit:
    #     image: rabbitmq:3

    web:
        build: ./
        working_dir: /code/web/
        command: python manage.py runserver 0.0.0.0:8000
        image: legacy-tos
        ports:
            - 8000:8000
        volumes:
            - media:/code/web/public/media
            - database:/code/db
        environment:
            DATABASE_DIR: /code/db/db.sqlite3
            DJANGO_SETTINGS_MODULE: treeofscience.settings.development

volumes:
    media:
    database:

